### ISSUE TITLE
05/04/2020 Code review

### ISSUE THREAD

**Issue by Victorgonbu** [carlos-ssh/html-form#2]
-You could use main tag after header tag
-Sign in button on the full screen should be on top of the screen and when it gets smaller should go above.
.in order to aling you topside with the main content, you should implement all icons on a division and style as a whole.
-recommendation to center content you should use display:flex and after doing that you could use along items to center.

keep on the good work and thanks for sharing!

**Comment by carlos-ssh** [comment]
thanks for giving us this support and now we have already fixed your suggestions.
